services:
  logger:
    class: Monolog\Logger
    arguments: 
      - main
      - ['@logger.stream.handler']
    calls:
      - [pushHandler, ['@logger.std_out_logger']]
      - [debug, ['The logger just got started']]
  
  logger.stream.handler:
    class: Monolog\Handler\StreamHandler
    arguments: [__DIR__.'/dino.log']
      
  logger.std_out_logger:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stdout']
    
  